### ISSUE TITLE
1.17 Server and Client / Decompilation error

### ISSUE THREAD

**Issue by ToshioDev** [ShaneBeeStudios/McDeob#12]
I tried to decompile version 1.17 and in the log i get the following error:

java.lang.IllegalArgumentException: Unsupported class file major version 60

**Comment by ShaneBeee** [comment]
Is there more to that error or is that it?

**Comment by crackedMagnet** [comment]
Yeah I'm getting the same thing

[12:06:07] [ERROR] [Processor]: Encountered an error while preparing
java.lang.IllegalArgumentException: Unsupported class file major version 60
	at org.objectweb.asm.ClassReader.<init>(ClassReader.java:195) ~[McDeob-2.1.33.jar:?]
	at org.objectweb.asm.ClassReader.<init>(ClassReader.java:176) ~[McDeob-2.1.33.jar:?]
	at org.objectweb.asm.ClassReader.<init>(ClassReader.java:162) ~[McDeob-2.1.33.jar:?]
	at org.objectweb.asm.ClassReader.<init>(ClassReader.java:283) ~[McDeob-2.1.33.jar:?]
	at io.github.lxgaming.reconstruct.Reconstruct.link(Reconstruct.java:146) [McDeob-2.1.33.jar:?]
	at io.github.lxgaming.reconstruct.Reconstruct.load(Reconstruct.java:123) [McDeob-2.1.33.jar:?]
	at com.shanebeestudios.mcdeop.Processor.remapJar(Processor.java:179) [McDeob-2.1.33.jar:?]
	at com.shanebeestudios.mcdeop.Processor.init(Processor.java:73) [McDeob-2.1.33.jar:?]
	at com.shanebeestudios.mcdeop.app.App$1.run(App.java:165) [McDeob-2.1.33.jar:?]

I've tried using JDK 16.0.1 and that doesn't seem to help.

**Comment by ShaneBeee** [comment]
Ok I did an update with a fix, I've tested on both java 15 and 16 and it worked.

Please let me know if this version works for you guys before I close this issue:
https://github.com/ShaneBeeStudios/McDeob/releases/tag/2.1.34

**Comment by crackedMagnet** [comment]
yeah its looking good so far.  at least it certainly getting further than it did.  So I think this issue is resolved.

**Comment by ShaneBeee** [comment]
ok cool.
Im going to close this issue, but if the problem persists, feel free to reopen it.
