### ISSUE TITLE
Unable to download the Mojang JAR file.

### ISSUE THREAD

**Issue by AvnyrTokirawa** [ShaneBeeStudios/McDeob#32]
After multiple attempts, having checked my firewall etc..
I always get the same error message.
Did Mojang change the download method?

> [19:43:16 ←[36mProcessor←[0m INFO]: Downloading JAR file from Mojang.

`java.net.SocketException: Connection reset
        at java.base/sun.nio.ch.NioSocketImpl.implRead(NioSocketImpl.java:320)
        at java.base/sun.nio.ch.NioSocketImpl.read(NioSocketImpl.java:347)
        at java.base/sun.nio.ch.NioSocketImpl$1.read(NioSocketImpl.java:800)
        at java.base/java.net.Socket$SocketInputStream.read(Socket.java:966)
        at java.base/sun.security.ssl.SSLSocketInputRecord.read(SSLSocketInputRecord.java:478)
        at java.base/sun.security.ssl.SSLSocketInputRecord.readFully(SSLSocketInputRecord.java:461)
        at java.base/sun.security.ssl.SSLSocketInputRecord.decodeInputRecord(SSLSocketInputRecord.java:243)
        at java.base/sun.security.ssl.SSLSocketInputRecord.decode(SSLSocketInputRecord.java:181)
        at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:111)
        at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1508)
        at java.base/sun.security.ssl.SSLSocketImpl.readApplicationRecord(SSLSocketImpl.java:1479)
        at java.base/sun.security.ssl.SSLSocketImpl$AppInputStream.read(SSLSocketImpl.java:1064)
        at java.base/java.io.BufferedInputStream.read1(BufferedInputStream.java:282)
        at java.base/java.io.BufferedInputStream.read(BufferedInputStream.java:343)
        at java.base/sun.net.www.MeteredStream.read(MeteredStream.java:141)
        at java.base/java.io.FilterInputStream.read(FilterInputStream.java:133)
        at java.base/sun.net.www.protocol.http.HttpURLConnection$HttpInputStream.read(HttpURLConnection.java:3663)
        at java.base/java.io.InputStream.transferTo(InputStream.java:782)
        at java.base/java.nio.file.Files.copy(Files.java:3172)
        at com.shanebeestudios.mcdeop.Processor.downloadJar(Processor.java:125)
        at com.shanebeestudios.mcdeop.Processor.init(Processor.java:87)
        at com.shanebeestudios.mcdeop.McDeob.lambda$main$0(McDeob.java:88)
        at java.base/java.lang.Thread.run(Thread.java:833)`
        
        I am under Windows and used the CLI

**Comment by AvnyrTokirawa** [comment]
Using version 2.2.0

**Comment by AvnyrTokirawa** [comment]
I also had another error which I think resulted in my ip being banned from their web server.

`java.net.ConnectException: Connection timed out: connect
        at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:67)
        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:483)
        at java.base/sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:2048)
        at java.base/sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:2043)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:569)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getChainedException(HttpURLConnection.java:2042)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1609)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1589)
        at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:224)
        at com.shanebeestudios.mcdeop.Processor.downloadJar(Processor.java:124)
        at com.shanebeestudios.mcdeop.Processor.init(Processor.java:87)
        at com.shanebeestudios.mcdeop.McDeob.lambda$main$0(McDeob.java:88)
        at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.net.ConnectException: Connection timed out: connect
        at java.base/sun.nio.ch.Net.connect0(Native Method)
        at java.base/sun.nio.ch.Net.connect(Net.java:579)
        at java.base/sun.nio.ch.Net.connect(Net.java:568)
        at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:585)
        at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327)
        at java.base/java.net.Socket.connect(Socket.java:633)
        at java.base/sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:304)
        at java.base/sun.security.ssl.BaseSSLSocketImpl.connect(BaseSSLSocketImpl.java:174)
        at java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:183)
        at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:498)
        at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:603)
        at java.base/sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:264)
        at java.base/sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:378)
        at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:189)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1242)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1128)
        at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:175)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1665)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1589)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getHeaderField(HttpURLConnection.java:3221)
        at java.base/java.net.URLConnection.getHeaderFieldLong(URLConnection.java:645)
        at java.base/java.net.URLConnection.getContentLengthLong(URLConnection.java:509)
        at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getContentLengthLong(HttpsURLConnectionImpl.java:372)
        at com.shanebeestudios.mcdeop.Processor.downloadJar(Processor.java:121)
        ... 3 more`

**Comment by ShaneBeee** [comment]
Using 2.2.0, I get this when running the actual app:
```
ShaneBee@Shanes-MacBook-Pro ~ % java -jar /Users/ShaneBee/IdeaProjects/McDeob/target/McDeob-2.2.0.jar 
[10:55:37 Processor INFO]: Downloading JAR file from Mojang.
[10:55:51 Processor INFO]: Successfully downloaded JAR file in 13 seconds!
[10:55:51 Processor INFO]: Downloading mappings file from Mojang...
[10:55:52 Processor INFO]: Successfully downloaded mappings file in 1 second!
[10:55:52 Processor INFO]: Remapping minecraft_server_1.19.2.jar file...
[Processor] INFO Reconstruct - Minecraft Bundler Detected
[Processor] INFO Reconstruct - - 1.19.2 (d79def2f9aaf06d6b851e568150762b8e7ee24a898a314cf34b210cbd9ea14b6)
[Processor] INFO Reconstruct - Extracting META-INF/versions/1.19.2/server-1.19.2.jar -> /Users/ShaneBee/McDeob/server-1.19.2.jar
[Processor] INFO Reconstruct - Overriding Input Path /Users/ShaneBee/McDeob/minecraft_server_1.19.2.jar -> /Users/ShaneBee/McDeob/server-1.19.2.jar
[Processor] INFO Reconstruct - Parsing mappings...
[Processor] INFO Reconstruct - Mapped:
[Processor] INFO Reconstruct -  - 5839 Classes
[Processor] INFO Reconstruct -  - 6750 Constructors
[Processor] INFO Reconstruct -  - 22513 Fields
[Processor] INFO Reconstruct -  - 37739 Methods
[Processor] INFO Reconstruct - Linking...
[Processor] INFO Reconstruct - Linked 5839 classes
[Processor] INFO Reconstruct - Transforming...
[Processor] INFO Reconstruct - Waiting for TransformTasks to complete...
[Processor] INFO Reconstruct - Waiting for WriteTask to complete...
[10:56:53 Processor INFO]: Remapping completed in 1 minute, !
[10:56:53 Processor INFO]: Completed in 1 minute, 16 seconds!
```

When running CLI I get this:
```
ShaneBee@Shanes-MacBook-Pro ~ % java -jar /Users/ShaneBee/IdeaProjects/McDeob/target/McDeob-2.2.0.jar  -version 1.19.2 -type server 
[11:01:28 Processor INFO]: Downloading JAR file from Mojang.
[11:01:43 Processor INFO]: Successfully downloaded JAR file in 14 seconds!
[11:01:43 Processor INFO]: Downloading mappings file from Mojang...
[11:01:45 Processor INFO]: Successfully downloaded mappings file in 2 seconds!
[11:01:45 Processor INFO]: Remapping minecraft_server_1.19.2.jar file...
[Processor] INFO Reconstruct - Minecraft Bundler Detected
[Processor] INFO Reconstruct - - 1.19.2 (d79def2f9aaf06d6b851e568150762b8e7ee24a898a314cf34b210cbd9ea14b6)
[Processor] INFO Reconstruct - Extracting META-INF/versions/1.19.2/server-1.19.2.jar -> /Users/ShaneBee/McDeob/server-1.19.2.jar
[Processor] INFO Reconstruct - Overriding Input Path /Users/ShaneBee/McDeob/minecraft_server_1.19.2.jar -> /Users/ShaneBee/McDeob/server-1.19.2.jar
[Processor] INFO Reconstruct - Parsing mappings...
[Processor] INFO Reconstruct - Mapped:
[Processor] INFO Reconstruct -  - 5839 Classes
[Processor] INFO Reconstruct -  - 6750 Constructors
[Processor] INFO Reconstruct -  - 22513 Fields
[Processor] INFO Reconstruct -  - 37739 Methods
[Processor] INFO Reconstruct - Linking...
[Processor] INFO Reconstruct - Linked 5839 classes
[Processor] INFO Reconstruct - Transforming...
[Processor] INFO Reconstruct - Waiting for TransformTasks to complete...
[Processor] INFO Reconstruct - Waiting for WriteTask to complete...
[11:02:44 Processor INFO]: Remapping completed in 59 seconds!
[11:02:44 Processor INFO]: Completed in 1 minute, 16 seconds!
```

That said, I can't replicate this issue.
Doing some quick googling, I came across this:
https://stackoverflow.com/questions/86824/why-would-a-java-net-connectexception-connection-timed-out-exception-occur-wh

**Comment by ShaneBeee** [comment]
Closing due to no further communication if issue was still there
