### ISSUE TITLE
Can't decompile jar file, getting unknownhostexception

### ISSUE THREAD

**Issue by Jakush** [ShaneBeeStudios/McDeob#45]
PS C:\Users\James\Downloads\1.20.6> java -jar McDeob-3.0.2.jar -version 1.20.6 -type server -decompile
Exception in thread "main" java.lang.RuntimeException: java.net.UnknownHostException: launchermeta.mojang.com
        at com.shanebeestudios.mcdeop.Version.initVersions(Version.java:23)
        at com.shanebeestudios.mcdeop.McDeob.main(McDeob.java:15)
Caused by: java.net.UnknownHostException: launchermeta.mojang.com
        at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:567)
        at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327)
        at java.base/java.net.Socket.connect(Socket.java:751)
        at java.base/sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:304)
        at java.base/sun.security.ssl.BaseSSLSocketImpl.connect(BaseSSLSocketImpl.java:181)
        at java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:183)
        at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:531)
        at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:636)
        at java.base/sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:264)
        at java.base/sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:377)
        at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:193)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1237)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1123)
        at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:179)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1675)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1599)
        at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:223)
        at com.shanebeestudios.mcdeop.util.Util.getJsonFromURL(Util.java:27)
        at com.shanebeestudios.mcdeop.Version.initVersions(Version.java:21)
        ... 1 more
PS C:\Users\James\Downloads\1.20.6>

**Comment by ShaneBeee** [comment]
I couldn't replicate this issue.
It looks like the website wasn't responding.
Have you tried again since?
