### ISSUE TITLE
Can't get past "Downloading JAR..."

### ISSUE THREAD

**Issue by jumpingfox27** [ShaneBeeStudios/McDeob#46]
I'm trying to get the server, but the exact same thing happens with the client.
My operating system is Windows 11 Home.

Here is the error I get in the console:

```
[00:03:34 ←[36mProcessor←[0m INFO]: Downloading JAR file from Mojang.
java.nio.file.NoSuchFileException: deobf-work\minecraft_server_1.21.1.jar
        at java.base/sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:85)
        at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103)
        at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:108)
        at java.base/sun.nio.fs.WindowsFileSystemProvider.newByteChannel(WindowsFileSystemProvider.java:236)
        at java.base/java.nio.file.spi.FileSystemProvider.newOutputStream(FileSystemProvider.java:484)
        at java.base/java.nio.file.Files.newOutputStream(Files.java:228)
        at java.base/java.nio.file.Files.copy(Files.java:3160)
        at com.shanebeestudios.mcdeob.Processor.downloadJar(Processor.java:129)
        at com.shanebeestudios.mcdeob.Processor.init(Processor.java:94)
        at com.shanebeestudios.mcdeob.app.App$1.run(App.java:185)
```

**Comment by jumpingfox27** [comment]
For whatever reason it works on my laptop (runs Windows 10 Home)?? Maybe it's just my computer being weird.

**Comment by ShaneBeee** [comment]
That is really weird. I can't find a way to replicate it.
Looking at the code, and the error... it appears the downloaded jar is either not saving to your PC or its in the wrong spot, which I dont see how that would happen on one computer and not the other. 
So Im stumped

**Comment by ShaneBeee** [comment]
> tbh, I think a good enough solution for this would to give the user the option to force a download of the file or not.
> 
> Right now, it will ALWAYS force a download of the jar when it detects the file is not the same file length, which is fine as it is a dummy way to make sure the file is not corrupt.
> 
> While this likely isn't run all the time, I have already downloaded the server jar and would be nice to just skip the download as it is a custom server jar.
> 
> maybe a `--force-download` option or `--use-cached` or something similar.

Thats a good idea, ill look into something like that.

**Comment by ShaneBeee** [comment]
Going to close this for now, as theres been no signs of this issue reoccurring
